name: Latest Blog Post Workflow
on:
  push:
  schedule: # Runs workflow automatically
    - cron: "0 */6 * * *" # Runs every 6 hours
jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://medium.com/feed/@cheezumcali23"
          show_feed_title: true
          show_feed_description: true
          show_read_more: true
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
      - name: Create Pull Reaquest
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Save Generated Blog Posts
          title: 'Automated Blog Post Update'
          body: 'This is an automated pull request to update blog posts.'
          base: main # The protected branch I want to merge into
          branch: blog-update # The branch with the new changes
