name: Latest blog post workflow
on:
  push:
  schedule: # Runs workflow automatically
    - cron: "0 0 * * *" # Runs at midnight UTC, every day 
jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://medium.com/feed/@cheezumcali23"
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
