name: Latest Blog Post Workflow

on:
  push:
  schedule: # Runs workflow automatically
    - cron: "0 */6 * * *" # Runs every 6 hours
jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://medium.com/feed/@cheezumcali23"
          show_feed_data: true
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Save Generated Blog Posts"
          branch: update-blog-posts # Change this to a non-protected branch

        
          
    

          
          

